#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx husky add .husky/pre-commit 'npx --no-install lint-staged'
npx --no-install lint-staged
npx --no-install lint-staged
npx --no-install lint-staged
